import sys
import os
mykr = 'SSW_mod'
myin = 'KR_goals.gfx'
myout = 'KR_goals_shine.gfx'
foundpath = None
mypath = os.path.realpath(__file__).split('\\')
print('Finding ' + mykr + '...')
while not foundpath:
    krpath = ''
    for item in mypath:
        krpath = krpath + '/' + item
        if 'mod' in item:
            krpath = krpath[1:] + '/' + mykr + '/interface/'
            print('검색중: ' + krpath[:-10])
            break

    if os.path.exists(krpath):
        print( mykr + '를 찾았습니다!')
        foundpath = True
    else:
        print("Can't find " + mykr + '...\n')
        mykr = input('Insert Your mod name : ')

foundname = None
foundlocation = None
inpath = krpath + myin
outpath = krpath + myout
if not os.path.exists(inpath):
    print('no KR_goals.gfx file found!')
    print('Checked path: ' + inpath)
    input('Press Enter to continue...')
    sys.exit()
print('Converting to shines...')
filein = open(inpath, 'r')
fileout = open(outpath, 'w')
fileout.write('spriteTypes = {')
fileout.write('\n')
fileout.write('\t#########################################\n')
fileout.write('\t###            Mod Shines             ###\n')
fileout.write('\t#########################################\n')
fileout.write('\t###   DO NOT EDIT THIS FILE MANUALLY  ###\n')
fileout.write('\t### RUN THE SHINEMAKER TOOL IN KR_AUX ###\n')
fileout.write('\t#########################################\n')
fileout.write('\n')
for line in filein:
    if line.lstrip()[:1] is not '#':
        spritelist = line.split('"')
        for index, item in enumerate(spritelist):
            if 'name =' in item:
                spritename = spritelist[(index + 1)]
                foundname = True
                print(spritename)
            if 'texturefile =' in item:
                spritelocation = spritelist[(index + 1)]
                foundlocation = True
            if foundname and foundlocation:
                fileout.write('\tSpriteType = {\n')
                fileout.write('\t\tname = "' + spritename + '_shine"\n')
                fileout.write('\t\ttexturefile = "' + spritelocation + '"\n')
                fileout.write('\t\teffectFile = "gfx/FX/buttonstate.lua"\n')
                fileout.write('\t\tanimation = {\n')
                fileout.write('\t\t\tanimationmaskfile = "' + spritelocation + '"\n')
                fileout.write('\t\t\tanimationtexturefile = "gfx/interface/goals/shine_overlay.dds"\n')
                fileout.write('\t\t\tanimationrotation = -90.0\n')
                fileout.write('\t\t\tanimationlooping = no\n')
                fileout.write('\t\t\tanimationtime = 0.75\n')
                fileout.write('\t\t\tanimationdelay = 0\n')
                fileout.write('\t\t\tanimationblendmode = "add"\n')
                fileout.write('\t\t\tanimationtype = "scrolling"\n')
                fileout.write('\t\t\tanimationrotationoffset = { x = 0.0 y = 0.0 }\n')
                fileout.write('\t\t\tanimationtexturescale = { x = 1.0 y = 1.0 }\n')
                fileout.write('\t\t}\n')
                fileout.write('\n')
                fileout.write('\t\tanimation = {\n')
                fileout.write('\t\t\tanimationmaskfile = "' + spritelocation + '"\n')
                fileout.write('\t\t\tanimationtexturefile = "gfx/interface/goals/shine_overlay.dds"\n')
                fileout.write('\t\t\tanimationrotation = 90.0\n')
                fileout.write('\t\t\tanimationlooping = no\n')
                fileout.write('\t\t\tanimationtime = 0.75\n')
                fileout.write('\t\t\tanimationdelay = 0\n')
                fileout.write('\t\t\tanimationblendmode = "add"\n')
                fileout.write('\t\t\tanimationtype = "scrolling"\n')
                fileout.write('\t\t\tanimationrotationoffset = { x = 0.0 y = 0.0 }\n')
                fileout.write('\t\t\tanimationtexturescale = { x = 1.0 y = 1.0 }\n')
                fileout.write('\t\t}\n')
                fileout.write('\t\tlegacy_lazy_load = no\n')
                fileout.write('\t}\n')
                fileout.write('\n')
                foundlocation = False
                foundname = False

fileout.write('}')
filein.close()
fileout.close()
print('완료!')
input('엔터를 눌러 계속하세요...')
sys.exit()